name: ml4ms
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - terminado
  - pywinpty
  - nodejs
  - vs2015_runtime
  - pyarrow=16.1.*
  - shap
  - imbalanced-learn
  - datasets