name: ml4ms
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - terminado
      - pywinpty
      - nodejs
      - shap
      - imbalanced-learn
      - datasets
      - pyarrow